### ISSUE TITLE
[BUG] Players still get flagged as PvP when entering opposing cities

### ISSUE THREAD

**Issue by Aldori15** [gitdalisar/mod-Faction-Free#2]
**Describe the bug:**
Players will still automatically be flagged for PvP when entering cities of the opposing faction.  For example, if you are Blood Elf and enter Stormwind City.  

**Steps To Reproduce:**
1. Enter into a city of the opposing faction.
2. Notice that the player has automatically been flagged for PvP.

**Screenshots:**
Example after converting Stormwind to a Sanctuary:
https://imgur.com/a/M0skeMm

**Suggested Resolution:**
I was able to resolve this by converting the cities into a Sanctuary by modifying the AreaTable.dbc file.  There may be other ways to resolve this, but I'm not sure how to directly say "Hey, don't enable the PvP flag automatically when I enter "x" area, but at least for me, converting it to a Sanctuary is a quick and easy way.

See below steps that I took for resolving this:

1. In game, go to the location you want to change to a Sanctuary and then type ".gps".  Note down the Zone ID.  My example of Stormwind City gave me a Zone ID of 1519.

2. Open AreaTable.dbc and find ID 1519 for Stormwind City.

3. Change the "Flags" column to one of the following numbers:  19496 (Sanctuary, no duels allowed), 19456 (Sanctuary, duels allowed).  For my example, I ended up using 19496.

4. Save the AreaTable.dbc file and drop it into both your server Data/dbc path, as well as the .MPQ patch for the client.

**Comment by Aldori15** [comment]
I finished converting all cities into Sanctuaries and that seems to do the trick.

**Comment by gitdalisar** [comment]
Wondering if this worked with you due to something with Dinkle's repack? I set capital cities to Sanctuary and still got flagged as PVP. Nobody will attack but it still does put me into PVP. Talking with the AC folks to see if I can run down where the other changes may need to be made. Could be an areatrigger that is putting you into PVP by walking into the zone.

**Comment by Aldori15** [comment]
Weird, I have no clue.  I'm not sure if this makes a difference or not, but you can also try this.  In addition to me setting the Capital City flag to 19496  (for example, .gps in Stormwind gives Zone ID 1519).  

I also filtered the ParentAreaID column by the Zone ID of the city (1519 for Stormwind, repeat for other cities).  I also set the flag for all of the sub areas within the capital city as well.  Did this for each capital city.

![image](https://github.com/gitdalisar/mod-Faction-Free/assets/15916673/adf11556-abdd-4a06-8259-7222dcfb888e)

![image](https://github.com/gitdalisar/mod-Faction-Free/assets/15916673/0b626b41-5822-4320-983b-9021d7484689)

**Comment by Aldori15** [comment]
Those are the only changes I made on my end to get it to work.  If it still doesn't work, then I'm not sure if Dinkle has something else in place.  All I know is that prior to me making this Flags sanctuary flag, I was getting flagged when walking into capital cities even on Dinkle's repack.

**Comment by gitdalisar** [comment]
Ahh good call, let me test that out tonight and I'll see if that's the ticket. I bet you're right and even though I was in say "Stormwind" if like "Stormwind Docs" still doesn't fly as sanc then yeah I bet that could be it. I'll give that a shot for like Stormwind, see if things are good, and if so roll from there. Thanks!

**Comment by gitdalisar** [comment]
Nope, still not it. The AreaTable.dbc I changed Stormwind as well as the two sub locations to be sanctuary, they are now, I zone and states as such. But I am still flagged as PVP on my horde character. I can still group with that horde character with an alliance, cast on it just fine, but that does put the alliance character into being pvp flagged as well. Now, since it is a sanctuary, I can't ATTACK the other faction, but it definitely is still getting flagged somewhere... I'll reach out to the AC discord again and see if they may have any idea, but definitely looks like some sort of divergence from Azerothcore and Dinkle's repack.

**Comment by gitdalisar** [comment]
Found the issue within the PlayerUpdate.cpp file. There were checks for if you were of the opposing walking into something flagged as a capital city then it put you into pvp. Commented out those checks and added the .cpp to repo as part of v1.2.0 release.
