### ISSUE TITLE
[BUG] attacked by pvp npc

### ISSUE THREAD

**Issue by GitVenyce** [gitdalisar/mod-Faction-Free#3]
**Describe the bug**
Attacked by PVP NPCs despite being friendly

**Comment by gitdalisar** [comment]
I am thinking this has to do with the enemy races within the FactionTemplate.dbc. I'm going to create a spreadsheet with a pivot to use faction.dbc to name the factions in factiontemplate.dbc to see if that may be the cause. They aren't showing as enemies, but still engage with the PVP flag next to their name. Could also need to just replace the factions with one that are not aggro.

**Comment by gitdalisar** [comment]
Tested this out and looks like we will just need to do some rep swaps. Tested this out against the Bluffwatchers in Thunder Bluff as an Alliance player and against King Varian in Stormwind as a Horde. Will take a look in other capital cities to test out this factional dispute as well as other areas like Hinterlands. Once the majority of these factions have been found, will update the FactionFree.sql file with the appropriate SQL changes.

**Comment by gitdalisar** [comment]
Okay so found the base factions that are used for world or pve type aggression. They appear to be:
1733 - Alliance PVP flagged NPCs - worldwide
1734 - Horde PVP flagged NPCs - worldwide
83 - Horde PVP flagged NPCs - worldwide - used in ICC airship battle
84 - Alliance PVP flagged NPCs - worldwide - used in ICC airship battle
106 - Horde PVP flagged NPCs - worldwide - Outland outposts
210 - Alliance PVP flagged NPCs - Outland outposts

In order to resolve this, needed to change all those to neutral (35) but still set the NPC spawned for the airship battle in ICC to be enemies (14). I also verified that the Argent Tournament is clean with no issues there. Also TOC (both raid and dungeon) the opposing factions are listed as 14 or 16 so no need to change there either. This should take care of anything I could find. If I missed anything it will be a small one off that I can adjust accordingly.

Testing this out now with the sql changes required and will move to repo once confirmed.

**Comment by VigilantFork** [comment]
I really love and believe in this mod...unfortunately I am away on vacation for another week. I'm very new to all of this so I look forward to helping you troubleshoot some of these other bugs. I'm new to this stuff, so if my post here (due to being more conversational in nature rather than working towards a goal) is out of line my apologies, but I just wanted to let you know that I enjoy what you're doing and am looking forward to contributing towards bug-hunting in the future!

**Comment by gitdalisar** [comment]
@VigilantFork Absolutely welcome the conversation and help! I have a thread going on the WoW Modding Discord in the Releases section that you can also chat on. Can also start convo in the Discussions section here. Whatever you'd like! These individual bugs/features will be closed out (like this one today) once I get the work completed! :)  I'd probably recommend the WoW Modding Discord for the chat, that's where most of the convo is going on!

**Comment by VigilantFork** [comment]
@gitdalisar Great -- I did join that discord so I'll correspond there if that's better once I get back, thank you!
